/**
 * 素材库元数据：中文名 + 分类规则。
 *
 * Lucide 图标名是英文且多达 1900+ 个，逐个人工翻译不现实，因此采用两层策略：
 * 1) `ZH` —— 人工覆盖的高频图标（约 300 个），提供准确中文名，直接支撑中文搜索；
 * 2) `CAT_RULES` —— 按图标名关键词自动归类，让未翻译的图标也能落到合适分类里浏览。
 *
 * 未命中的图标仍可通过英文原名搜索，不会不可用。
 */

/** Lucide 图标 kebab 名 → 中文名 */
export const ZH: Record<string, string> = {
  // ── 包装 / 仓储 / 物流 ──
  package: '包裹',
  'package-2': '包裹2',
  'package-open': '开箱',
  'package-plus': '新增包裹',
  'package-minus': '减少包裹',
  'package-x': '包裹不可用',
  'package-check': '包裹已验',
  'package-search': '包裹查询',
  boxes: '箱堆',
  container: '集装箱',
  warehouse: '仓库',
  'luggage': '行李',
  truck: '货车',
  ship: '货轮',
  sailboat: '帆船',
  anchor: '船锚',
  plane: '飞机',
  'plane-takeoff': '起飞',
  'plane-landing': '降落',
  rocket: '火箭',
  'train-front': '列车头',
  bus: '大巴',
  car: '汽车',
  bike: '自行车',
  'car-front': '车头',
  'route': '路线',
  'map': '地图',
  'map-pin': '位置标记',
  'map-pinned': '已定位置',
  'navigation': '导航',
  'compass': '罗盘',
  'globe': '全球',
  'fuel': '燃油',
  'milestone': '里程碑',
  'signpost': '路标',
  'list-ordered': '序号列表',
  'clipboard-list': '清单',
  'clipboard-check': '验收单',

  // ── 认证 / 品质 / 评价 ──
  'badge-check': '认证徽章',
  'circle-check': '圆形勾',
  'circle-check-big': '大圆勾',
  'check': '勾',
  'check-check': '双勾',
  'shield': '盾牌',
  'shield-check': '安全认证',
  'shield-alert': '安全警告',
  'shield-x': '未认证',
  'award': '奖项',
  'medal': '奖章',
  'trophy': '奖杯',
  'star': '星',
  'star-half': '半星',
  'sparkle': '闪耀',
  'sparkles': '闪亮',
  'gem': '宝石',
  'crown': '皇冠',
  'stamp': '印章',
  'id-card': '证件',
  'scroll-text': '证书',
  'file-check': '文件已核',
  'file-badge': '荣誉文件',
  'thumbs-up': '点赞',
  'thumbs-down': '点踩',
  'heart': '心',
  'heart-handshake': '合作',

  // ── 环保 / 回收 ──
  'recycle': '回收利用',
  'trash': '垃圾桶',
  'trash-2': '删除',
  'leaf': '叶子',
  'leafy-green': '绿叶',
  'trees': '树林',
  'tree-pine': '松树',
  'flower': '花',
  'sprout': '发芽',
  'wheat': '麦穗',
  'droplet': '水滴',
  'droplets': '防潮水珠',
  'waves': '波纹',
  'wind': '风',
  'sun': '太阳',
  'moon': '月亮',
  'cloud': '云',
  'cloud-rain': '下雨',
  'cloud-snow': '下雪',
  'cloud-sun': '晴转多云',
  'rainbow': '彩虹',
  'snowflake': '雪花',
  'biohazard': '生物危害',
  'radiation': '辐射',
  'skull': '骷髅毒性',
  'flame': '火焰',
  'cigarette': '香烟',

  // ── 安全 / 警告 ──
  'triangle-alert': '警告三角',
  'octagon-alert': '八角警示',
  'circle-alert': '圆形警示',
  'alert-triangle': '警告三角',
  'ban': '禁止',
  'circle-slash': '禁用',
  'lock': '锁',
  'lock-open': '开锁',
  'unlock': '解锁',
  'key': '钥匙',
  'key-round': '圆钥匙',
  'eye': '眼睛',
  'eye-off': '不可见',
  'ear-off': '静音',
  'volume-off': '静音喇叭',
  'hand': '手',
  'badge-alert': '徽章警告',
  'alert-circle': '警告圆',
  'siren': '警报器',
  'briefcase-medical': '急救',
  'life-buoy': '救生圈',
  'fire-extinguisher': '灭火器',
  'alarm-clock': '闹钟',
  'crosshair': '准心',
  'focus': '对焦',
  'scan': '扫描',
  'scan-barcode': '扫描条码',
  'qr-code': '二维码',
  'barcode': '条形码',

  // ── 温度 / 储运环境 ──
  'thermometer': '温度计',
  'thermometer-sun': '高温',
  'thermometer-snowflake': '低温',
  'gauge': '仪表',
  'weight': '称重',
  'scale': '天平',
  'scale-3d': '三维天平',
  'ruler': '尺子',
  'move-3d': '立体移动',
  'timer': '计时秒表',
  'clock': '时钟',
  'hourglass': '沙漏',
  'calendar': '日历',
  'calendar-clock': '日程时间',
  'history': '历史',
  'refresh-cw': '循环刷新',
  'rotate-cw': '顺时针旋转',
  'rotate-ccw': '逆时针旋转',

  // ── 箭头 / 方向 ──
  'arrow-up': '向上',
  'arrow-down': '向下',
  'arrow-left': '向左',
  'arrow-right': '向右',
  'arrow-big-up': '大箭头向上',
  'arrow-up-down': '上下双箭头',
  'chevrons-up-down': '上下拖拽',
  'arrow-up-right': '右上',
  'arrow-down-right': '右下',
  'arrow-down-left': '左下',
  'arrow-up-left': '左上',
  'arrow-up-to-line': '顶到线',
  'arrow-down-to-line': '底到线',
  'chevrons-up': '双箭向上',
  'chevrons-down': '双箭向下',
  'chevrons-left': '双箭向左',
  'chevrons-right': '双箭向右',
  'chevron-up': '折叠向上',
  'chevron-down': '折叠向下',
  'move-up': '上移',
  'move-down': '下移',
  'move-left': '左移',
  'move-right': '右移',
  'move-vertical': '纵向',
  'move-horizontal': '横向',
  'move-diagonal': '斜向',
  'corner-up-left': '左上折返',
  'corner-up-right': '右上折返',
  'corner-down-left': '左下折返',
  'corner-down-right': '右下折返',
  'redo': '重做',
  'undo': '撤销',
  'rotate-3d': '三维旋转',
  'flip-horizontal': '水平翻转',
  'flip-vertical': '垂直翻转',
  'swords': '交叉',
  'iteration-cw': '迭代',

  // ── 形状 / 符号 ──
  'circle': '圆',
  'circle-dashed': '虚线圆',
  'circle-dot': '点圆',
  'square': '方',
  'square-check': '方框勾',
  'square-dashed': '虚线方框',
  'triangle': '三角形',
  'triangle-dashed': '虚线三角',
  'diamond': '菱形',
  'hexagon': '六边形',
  'pentagon': '五边形',
  'octagon': '八边形',
  'octagon-x': '八角叉',
  'percent': '百分号',
  'infinity': '无穷',
  'plus': '加号',
  'minus': '减号',
  'x': '叉号',
  'divide': '除号',
  'equal': '等号',
  'hash': '井号',
  'asterisk': '星号',
  'copyright': '版权符号',
  'sigma': '求和',
  'omega': '欧姆',

  // ── 文本 / 排版 ──
  'type': '文本',
  'heading': '标题',
  'heading-1': '一级标题',
  'heading-2': '二级标题',
  'heading-3': '三级标题',
  'bold': '加粗',
  'italic': '斜体',
  'underline': '下划线',
  'strikethrough': '删除线',
  'align-left': '左对齐',
  'align-center': '居中对齐',
  'align-right': '右对齐',
  'align-justify': '两端对齐',
  'list': '列表',
  'list-todo': '待办列表',
  'quote': '引用',
  'text': '文字',
  'text-cursor': '文本光标',
  'case-upper': '大写',
  'case-lower': '小写',
  'baseline': '基线',
  'pilcrow': '段落符',
  'space': '空格',

  // ── 通信 / 联络 ──
  'phone': '电话',
  'phone-call': '来电',
  'mail': '邮件',
  'mail-open': '开信',
  'message-circle': '消息',
  'message-square': '对话框',
  'send': '发送',
  'rss': '订阅',
  'megaphone': '喇叭',
  'volume-2': '音量',
  'wifi': '无线网',
  'wifi-off': '无网络',
  'bluetooth': '蓝牙',
  'share': '分享',
  'share-2': '分享2',
  'link': '链接',
  'at-sign': '艾特',
  'contact': '联系人',
  'user': '用户',
  'users': '多用户',
  'user-check': '已认证用户',

  // ── 工具 / 编辑 ──
  'settings': '设置',
  'settings-2': '设置2',
  'wrench': '扳手',
  'hammer': '锤子',
  'pencil': '铅笔',
  'pen': '钢笔',
  'eraser': '橡皮',
  'scissors': '剪刀',
  'paperclip': '回形针',
  'pin': '图钉',
  'pin-off': '取消图钉',
  'copy': '复制',
  'clipboard': '剪贴板',
  'clipboard-copy': '复制板',
  'layers': '图层堆叠',
  'layers-2': '图层',
  'layers-3': '多层',
  'paintbrush': '画笔',
  'palette': '调色盘',
  'pipette': '吸色管',
  'grid': '网格',
  'layout-grid': '布局网格',
  'search': '搜索',
  'zoom-in': '放大',
  'zoom-out': '缩小',
  'maximize': '最大化',
  'minimize': '最小化',
  'crop': '裁剪',
  'frame': '相框',
  'mouse-pointer': '鼠标指针',
  'hand-grab': '拖拽',
  'save': '保存',
  'download': '下载',
  'upload': '上传',
  'folder': '文件夹',
  'file': '文件',
  'files': '多文件',
  'file-text': '文档',
  'printer': '打印机',

  // ── 商业 / 支付 ──
  'shopping-cart': '购物车',
  'shopping-bag': '购物袋',
  'shopping-basket': '购物篮',
  'credit-card': '银行卡',
  'wallet': '钱包',
  'banknote': '钞票',
  'coins': '硬币',
  'dollar-sign': '美元',
  'receipt': '小票',
  'calculator': '计算器',
  'chart-line': '折线图',
  'chart-bar': '柱状图',
  'chart-pie': '饼图',
  'trending-up': '上涨',
  'trending-down': '下跌',
  'briefcase': '公文包',
  'building': '大楼',
  'factory': '工厂',
  'store': '商店',
  'tag': '标签',
  'tags': '多标签',
  'ticket': '票',
  'gift': '礼物',
  'handshake': '握手洽谈',

  // ── 几何 / 装饰点缀 ──
  'dna': '双螺旋',
  'atom': '原子',
  'orbit': '轨道',
  'puzzle': '拼图',
  'target': '靶心',
  'flag': '旗帜',
  'bookmark': '书签',
  'lightbulb': '灯泡',
  'zap': '闪电',
}

/**
 * Lucide 自动分类规则（按顺序取首个命中）。
 * 用于给未人工翻译的图标归类，保证「按分类浏览」始终可用。
 */
export const CAT_RULES: { id: string; label: string; match: RegExp }[] = [
  {
    id: 'logistics',
    label: '包装物流',
    match:
      /^(package|box|boxes|container|warehouse|pallet|truck|ship|boat|sail|plane|anchor|forklift|luggage|train|bus|car|bike|rocket|route|map|navigation|compass|milestone|signpost|crane|road|parcel)/,
  },
  {
    id: 'certify',
    label: '认证品质',
    match: /^(badge|award|medal|trophy|certificate|shield|check|verified|ribbon|seal|stamp|gem|crown|star|sparkle)/,
  },
  {
    id: 'safety',
    label: '安全警示',
    match: /alert|warning|danger|hazard|ban|lock|key|eye-|radiation|biohazard|skull|flame|siren|first-aid|fire|toxic/,
  },
  {
    id: 'arrow',
    label: '箭头方向',
    match: /^(arrow|chevron|move-|corner-|redo|undo|rotate|flip|iteration|shuffle|repeat|switch|transfer|maximize|minimize)/,
  },
  {
    id: 'storage',
    label: '环境储运',
    match: /thermometer|snowflake|sun|moon|cloud|rain|droplet|humidity|wind|rainbow|icing|zap|flame|frost/,
  },
  { id: 'recycle', label: '环保回收', match: /recycle|trash|leaf|tree|flower|sprout|wheat|seed|plant|earth|globe/ },
  { id: 'text', label: '文本排版', match: /^(type|heading|bold|italic|underline|strikethrough|align|list|quote|text|case-|baseline|pilcrow|font|sub|super)/ },
  { id: 'shape', label: '形状符号', match: /^(circle|square|triangle|diamond|hexagon|pentagon|octagon|ellipse|decagon|percent|infinity|plus|minus|hash|asterisk|copyright|registered|trademark|sigma|omega|slash)/, },
  { id: 'code', label: '条码信息', match: /barcode|qr|scan|input| Binary|binary|qr-code|receipt|tag|tags|hash/ },
  { id: 'device', label: '设备通信', match: /phone|mail|message|send|wifi|bluetooth|antena|signal|network|monitor|laptop|tv|printer|mouse|keyboard|hard-drive|usb|battery|plug|cable|cpu|server|cloud/ },
  { id: 'time', label: '时间日程', match: /clock|calendar|timer|hourglass|alarm|history|watch|stopwatch|fast-forward|pause|play|skip/ },
  { id: 'measure', label: '计量单位', match: /gauge|weight|scale|ruler|measure|percent|calculator|chart|trending|activity|coin|circle-dot/ },
  { id: 'edit', label: '编辑工具', match: /^(pencil|pen|eraser|scissors|copy|clipboard|layers|paintbrush|palette|pipette|grid|search|zoom|crop|frame|save|download|upload|folder|file|settings|wrench|hammer|brush|HTML)/ },
]

/** 默认分类 */
export const DEFAULT_CAT = { id: 'general', label: '通用' }
/** 储运标志专用分类（symbols 数据集整体归入） */
export const TRANSPORT_CAT = { id: 'transport', label: '储运标志' }

/** 按规则把 lucide 图标归类 */
export function categorizeLucide(name: string): string {
  for (const r of CAT_RULES) {
    if (r.match.test(name)) return r.id
  }
  return DEFAULT_CAT.id
}
